version: '2'
services:
  git-ci-legacy:
    build: dockerfiles/git-ci-legacy
    network_mode: none # deny access to actual git repositories
    volumes:
      - .:/olcs-ci:ro # mount everything in this dir - :ro = read-only
      - /olcs-ci/shell/repos # mount a volume in which to clone the repos
      - origin:/origin # fake origin location

  git-recent:
    build: dockerfiles/git-recent
    network_mode: none # deny access to actual git repositories
    volumes:
      - .:/olcs-ci:ro # mount everything in this dir - :ro = read-only
      - /olcs-ci/shell/repos # mount a volume in which to clone the repos
      - origin:/origin # fake origin location

volumes:
  origin: {}
